spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sb-03-data?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: secret_mysql
    driver-class-name: com.mysql.cj.jdbc.Driver