# mvn spring-boot:run

### If you open a web browser to localhost:8080, you should see the following output:
### Hello World!

GET http://localhost:8080/


# As DevTools monitors classpath resources, the only way to trigger a restart is to update the classpath. Whether you’re using an IDE or one of the build plugins, the modified files have to be recompiled to trigger a restart. The way in which you cause the classpath to be updated depends on the tool that you are using:
#   - In Eclipse, saving a modified file causes the classpath to be updated and triggers a restart.
#   - In IntelliJ IDEA, building the project (Build +→+ Build Project) has the same effect.
#   - If using a build plugin, running mvn compile for Maven or gradle build for Gradle will trigger a restart.
### Build -> Build Project
GET http://localhost:8080/

