spring:
  web:
    resources:
      # Locations of static resources.
      # Defaults to classpath:[/META-INF/resources/, /resources/, /static/, /public/].
      static-locations: ["classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/"]

  mvc:
    # Path pattern used for static resources.
    # "/custom-yourself/**"
    static-path-pattern: "/**"

  jackson:
    time-zone: Asia/Shanghai